
UPDATE public.proposal_templates
SET blocks = jsonb_set(
  blocks::jsonb,
  '{4,html}',
  to_jsonb($html$<div style="box-sizing:border-box;width:100%;max-width:900px;min-height:500px;width:760px;max-width:760px;margin:0 auto;padding:48px;border-radius:16px;overflow:hidden;display:flex;flex-direction:column;justify-content:center;font-family:Inter,system-ui,sans-serif;background:#f8fafc;color:#0f172a;"><div style="display:inline-block;background:#22c55e;color:#fff;padding:6px 14px;border-radius:999px;font-size:13px;font-weight:600;letter-spacing:.08em;text-transform:uppercase;margin-bottom:18px;">Próximos passos</div><h2 style="font-size:34px;margin:0 0 20px;font-weight:800;color:#064e3b;">Implantação e Investimento</h2><div style="display:grid;grid-template-columns:1.1fr 1fr;gap:22px;"><div><div style="font-size:13px;font-weight:700;color:#16a34a;letter-spacing:.1em;text-transform:uppercase;margin-bottom:10px;">Cronograma</div><ol style="margin:0;padding-left:20px;font-size:14px;line-height:1.7;color:#334155;"><li><strong>Kick-off</strong> — alinhamento e setup (semana 1).</li><li><strong>Configuração</strong> — filtros, perfis e usuários (semana 2).</li><li><strong>Treinamento</strong> — capacitação da equipe (semana 3).</li><li><strong>Go-live</strong> — operação assistida (semana 4).</li></ol></div><div style="display:flex;flex-direction:column;gap:14px;"><div style="background:#ffffff;border:2px solid #22c55e;border-radius:12px;padding:18px;"><div style="font-size:12px;font-weight:700;color:#16a34a;letter-spacing:.1em;text-transform:uppercase;margin-bottom:6px;">Implantação</div><div style="font-size:13px;color:#475569;margin-bottom:8px;">Setup, configuração e treinamento</div><div style="font-size:26px;font-weight:800;color:#064e3b;line-height:1;">{{opportunity.implementation_value}}</div><div style="font-size:12px;color:#64748b;margin-top:6px;">Pagamento único</div></div><div style="background:#ffffff;border:2px solid #22c55e;border-radius:12px;padding:18px;"><div style="font-size:12px;font-weight:700;color:#16a34a;letter-spacing:.1em;text-transform:uppercase;margin-bottom:6px;">Mensalidade</div><div style="font-size:13px;color:#475569;margin-bottom:8px;">Plano i-Ganhei — assinatura</div><div style="font-size:26px;font-weight:800;color:#064e3b;line-height:1;">{{opportunity.monthly_value}}</div><div style="font-size:12px;color:#64748b;margin-top:6px;">/mês</div><div style="margin-top:12px;padding-top:10px;border-top:1px dashed #cbd5e1;font-size:12px;color:#475569;">Valor total: <strong>{{opportunity.value}}</strong></div></div></div></div></div>$html$::text),
  true
)
WHERE id = '9ac64afe-2213-4ceb-89c0-1bad0b83df87';
